// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 10
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){






var ib=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var jb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,kb=function(a){if(null==a)return String(a);var b=jb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},lb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ta=function(a){if(!a||"object"!=kb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!lb(a,"constructor")&&!lb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||lb(a,b)},Ca=function(a,b){var c=b||("array"==kb(a)?[]:{}),d;for(d in a)if(lb(a,d)){var e=a[d];"array"==kb(e)?("array"!=kb(c[d])&&(c[d]=[]),c[d]=Ca(e,c[d])):ta(e)?(ta(c[d])||(c[d]={}),c[d]=Ca(e,c[d])):c[d]=e}return c};var Va=null,mb=Math.random(),nb=null,ka=null,Aa=!1,ob={},pb={},Ba={};var Da,Ea,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,V,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,
ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf;
(function(){var a=function(a){return{toString:function(){return a}}};qb=a("");rb=a("");sb="";tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("0");V=a("1");Cb=a("");Db=a("");Eb=a("");
Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");
Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("2");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");
jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");
Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");
Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");Da=a("3");ad=a("");bd=a("8");cd=a("9");dd=a("");ed=a("");
fd=a("4");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");Ea=a("5");md=a("");nd=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");
zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("6");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");
Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");
le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("7");Ae=
a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");
Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We="";Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=
a("");jf=a("");kf=a("");lf=a("");mf=a("")})();var eb=function(){},P=function(a){return"function"==typeof a},T=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},nf=function(a){return"number"==kb(a)&&!isNaN(a)},of=function(a){return/^[0-9]+$/.test(a)},pf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ja=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},R=function(a){return Math.round(Number(a))||0},xa=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},qf=function(a){var b=[];if(T(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},I=function(){return new Date},qa=function(a,b){if(!nf(a)||!nf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},rf=function(){this.prefix="gtm.";this.values={}};rf.prototype.set=function(a,b){this.values[this.prefix+a]=b};rf.prototype.get=function(a){return this.values[this.prefix+a]};rf.prototype.contains=function(a){return void 0!==this.get(a)};
var sf=function(a,b,c){try{if(!a[Bd])return a[Da](a,b||eb,c||eb);c&&c()}catch(d){}return!1},vf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ja(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},wf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},xf=function(a){return function(){return a("GTM-WLCZGN")}},yf=function(a){for(var b=0;b<a.length;b++)a[b]()},sa=function(){return"gtm"+zf()},
zf=function(){var a=Va.sequence||0;Va.sequence=a+1;return a},ua=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Af=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Bf=function(a,b){0==b?a.hb=!0:a.Z=!0;var c=a.g;a.i&&(a.i.Ma[c]=b);ob[c]&&(ob[c].state=b)},Cf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var z=window,L=document,Ef=navigator,S=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},K=function(a,b,c,d){return(d||"http:"!=z.location.protocol?a:b)+c},Ff=function(a){var b=L.getElementsByTagName("script")[0]||L.body||L.head;b.parentNode.insertBefore(a,b)},Za=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=L.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;Za(d,b);c&&(d.onerror=c);Ff(d);return d},ea=function(a,b){var c=L.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Ff(c);Za(c,b);void 0!==a&&(c.src=a);return c},H=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},u=function(a){z.setTimeout(a,0)},ab=!1,
bb=[],Gf=function(a){if(!ab){var b=L.createEventObject,c="complete"==L.readyState,d="interactive"==L.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ab=!0;for(var e=0;e<bb.length;e++)u(bb[e])}bb.push=function(){for(var a=0;a<arguments.length;a++)u(arguments[a]);return 0}}},Hf=0,If=function(){if(!ab&&140>Hf){Hf++;try{L.documentElement.doScroll("left"),Gf()}catch(a){z.setTimeout(If,50)}}},ga=function(a){var b=L.getElementById(a);if(b&&ha(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ha(document.all[a][c],
"id")==a)return document.all[a][c];return b},ha=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Qa=function(a){return a.target||a.srcElement||{}},ia=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},hb=function(a){var b=L.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
Ra=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Jf=!1,Kf=[],Lf=function(){if(!Jf){Jf=!0;for(var a=0;a<Kf.length;a++)u(Kf[a])}},Mf=function(a){a=a||z;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},fb=function(a){window.console&&window.console.log&&window.console.log(a)};var oa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||z.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||z.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:z.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=pf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},na=function(a){var b="";if(a&&a.href)var c=a.href.indexOf("#"),b=0>c?a.href:a.href.substr(0,c);
return b},ma=function(a){var b=L.createElement("a");a&&(b.href=a);return b};var ya=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a,b,c){H(a,b,c)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=oa(ma(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},N=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Xa=function(a,b){for(var c=
[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c};var Nf=new rf,Of={},Qf={set:function(a,b){Ca(Pf(a,b),Of)},get:function(a){return W(a,2)},reset:function(){Nf=new rf;Of={}}},W=function(a,b){if(2==b){var c=a.split(".");for(var f=Of,e=0;e<c.length;e++){if(void 0===f[c[e]])return;f=f[c[e]]}return f}return Nf.get(a)},Rf=function(a,b){Nf.set(a,b);Ca(Pf(a,b),Of)},Pf=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Sf=!1,Tf=!1;var Uf=Math.random(),Vf="0.100000">Uf;
var Wf=function(a,b){if(Vf){var c="//www.googletagmanager.com/a?id=GTM-WLCZGN&cv=10",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",I().getTime()-R(nb));c+="&sr=0.100000";d("&ps=",Uf);d("&cb=",qa());H(c)}},Xf=eb,Yf=function(){var a=!1;};var $f=function(a){var b=Va.zones;return b?b.checkState("GTM-WLCZGN",a):Zf},Zf={active:!0,isWhitelisted:function(){return!0}};var bg=eb,cg=[],dg=!1,ra=function(a){return z["dataLayer"].push(a)},eg=function(a){var b=!1;return function(){!b&&P(a)&&u(xf(a));b=!0}},kg=function(){for(var a=!1;!dg&&0<cg.length;){dg=!0;var b=cg.shift();if(P(b))try{b.call(Qf)}catch(Fa){}else if(T(b))a:{var c=b;if("string"==kb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Of,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Fa){}}}else{var m=void 0,n=void 0,q=b;for(n in q)q.hasOwnProperty(n)&&Rf(n,q[n]);var w=!1,y=q.event;if(y){q.hasOwnProperty("gtm.uniqueEventId")||(q["gtm.uniqueEventId"]=zf(),Rf("gtm.uniqueEventId",q["gtm.uniqueEventId"]));m=q["gtm.uniqueEventId"];ka=y;var t=$f(m);if(t.active){var x=eg(q.eventCallback),C=q.eventTimeout;
C&&z.setTimeout(x,Number(C));w=bg(m,y,t.isWhitelisted,x,q.eventReporter)}}nb||(nb=q["gtm.start"])&&Xf();var A=q,B=m,J=y,F=Of;if(!w){var E=m,G=y;}ka=null;a=w||a}var M=b,O=Of;jg();dg=!1}return!a},lg=function(){var a=kg();try{var b=z["dataLayer"].hide;if(b&&void 0!==b["GTM-WLCZGN"]&&b.end){b["GTM-WLCZGN"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},mg=function(){var a=S("dataLayer",[]),b=S("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};bb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});
Kf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(cg.push.apply(cg,b);300<this.length;)this.shift();return kg()};cg.push.apply(cg,a.slice(0));u(lg)};var Pa=function(a,b,c){U(a,b,c,void 0)},ba=function(a,b,c){r(a,b,c)},Q=function(a,b){return W(a,b||2)},aa=function(a,b){z[a]=b},p=function(a,b,c){var d=z;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},v=function(a,b,c,d){return(d||"http:"!=z.location.protocol?a:b)+c};var ng=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),og={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},pg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},qg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},rg=function(a){var b=W("gtm.whitelist");
var c=b&&qg(qf(b),og),d=W("gtm.blacklist")||W("tagTypeBlacklist")||[];ng.test(z.location&&z.location.hostname)&&(d=qf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&qg(qf(d),pg),f={};return function(g){var h=g&&g[Da];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>pf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
pf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var q;if(!(q=0<=pf(e,h.a)))a:{for(var w=h.b||[],y=new rf,t=0;t<e.length;t++)y.set(e[t],!0);for(t=0;t<w.length;t++)if(y.get(w[t])){q=!0;break a}q=!1}n=q}return f[h.a]=!k||n}};var fa=function(a){var b=L;return sg?b.querySelectorAll(a):null},tg=!1;if(L.querySelectorAll)try{var ug=L.querySelectorAll(":root");ug&&1==ug.length&&ug[0]==L.documentElement&&(tg=!0)}catch(a){}var sg=tg;var vg=void 0,wg="",xg=0,yg=void 0,_et=function(a){var b,c=W("gtm.element"),d=W("event"),e=Number(I());vg===c&&wg===d&&xg>e-250?b=yg:(yg=b=c?ia(c):"",vg=c,wg=d);xg=e;return b?b:a[yc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(W("gtm.elementUrl")||a[yc]||""),c=ma(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return ka};_e.a="e";_e.b=["google"];var zg=/(^|\.)doubleclick\.net$/i,Ag=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ta=function(a){for(var b=String(L.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=ja(e[0]);if(f&&f==a){var g=ja(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Bg=function(a,b,c,d,e){if(zg.test(L.location.hostname)||"/"==c&&Ag.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=L.cookie;L.cookie=f;return g!=
L.cookie||0<=pf(Ta(a),b)},Cg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Dg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Eg=function(){var a=oa(z.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Fg=function(a,b){this.h=a;this.o=b};Fg.prototype.toString=function(){var a=""+this.h;1<this.o&&(a=a+"-"+this.o);return a};var Gg=function(a,b){this.Ka=a;this.pa=b};Gg.prototype.toString=function(){return""+this.pa+"."+this.Ka};var Jg=function(a,b){var c=new Hg(null,a,b);Ig(c);return c},Hg=function(a,b,c){this.Wa=Math.floor(I().getTime()/864E5);this.oa=b||"auto";this.fa=c||"/";var d=Cg(this.oa),e=Dg(this.fa);this.H=a||new Fg(d,e);this.j=[];this.D=new rf},Lg=function(a,b,c){b&&(""==c.Ka?Kg(a,b):(a.D.contains(b)||a.j.push(b),a.D.set(b,c)))},Mg=function(a,b){for(var c=0;c<b.length;c++)Lg(a,b[c][0],b[c][1])},Kg=function(a,b){var c=pf(a.j,b);0<=c&&a.j.splice(c,1);a.D.set(b,void 0)},Ng=function(a){for(var b=[],c=0;c<a.j.length;c++){var d=
a.j[c];b.push([d,a.D.get(d)])}return b},Og=function(a){for(var b=0,c=0;c<a.j.length;c++)b=Math.max(b,a.D.get(a.j[c]).pa);return 864E5*b};Hg.prototype.toString=function(){if(0==this.j.length)return"";for(var a=[],b=0;b<this.j.length;b++){var c=this.j[b];a.push(""+c+"."+this.D.get(c).toString())}return"GAX1."+this.H.toString()+"."+a.join("!")};
var Pg=function(a,b){for(var c=new Date,d=Dg(a.fa),e=[],f=0;f<a.j.length;f++){var g=a.j[f];a.D.get(g).pa<a.Wa&&e.push(g)}for(f=0;f<e.length;f++)Kg(a,e[f]);if(a.j.length>(b||10))return!1;c.setTime(Og(a));if("auto"!=a.oa)return Bg("_gaexp",a.toString(),a.fa,a.oa,c);for(var h=Eg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.H=new Fg(Cg(h[k]),d),Bg("_gaexp",a.toString(),a.fa,h[k],c)))return!0;return!1},Ig=function(a){for(var b=a.H.h,c=a.H.o,d=Ta("_gaexp"),e=[],f=0;f<d.length;f++){var g=Qg(a,d[f]);g&&e.push(g)}Cf(e,
function(a,d){var e=a.H,f=d.H;return e.h==f.h&&e.o==f.o?!1:e.h==b&&e.o==c?!0:f.h==b&&f.o==c?!1:e.h==b?f.h!=b||e.o<f.o:f.h==b?!1:e.o==c?f.h!=b&&(f.o!=c||e.h<f.h):f.o==c?!1:e.h<f.h||e.h==f.h&&e.o<f.o});a.H=0<e.length?e[0].H:new Fg(b,c);for(f=e.length-1;0<=f;f--)Mg(a,Ng(e[f]))},Qg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ja(e[0]);if(0!=f.length){var g=2==e.length?ja(e[1]):"1";if(of(f)&&of(g)){d=new Fg(R(f),R(g));
break a}}}d=void 0}if(d){for(var h=new Hg(d,a.oa,a.fa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!of(m[1]))return;Lg(h,m[0],new Gg(m[2],R(m[1])))}}return h}}};var _v=function(a){var b=W(a[Hd].replace(/\\\./g,"."),a[qc]);return void 0!==b?b:a[yc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(W("gtm.referrer")||L.referrer);if(!b)return b;var c=ma(b);return b};_f.a="f";_f.b=["google"];var Ug=function(a){var b=z.location,c;(c=a[nc]?a[nc]:W("gtm.url"))&&(b=ma(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Zb]&&(f=oa(b,a[Zb],a[te],a[xc],a[ge]));return f},_u=Ug;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Bb])==String(a[V])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[V],a[hd]?"i":void 0)).test(a[Bb])};_re.a="re";_re.b=["google"];var Ua=new String("undefined"),cb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Ua?b:a[d]);return c.join("")}};cb.prototype.toString=function(){return this.resolve("undefined")};cb.prototype.valueOf=cb.prototype.toString;var dh={},db=function(a,b){var c=zf();dh[c]=[a,b];return c},eh=function(a){var b=a?0:1;return function(a){var c=dh[a];if(c&&P(c[b]))c[b]();dh[a]=void 0}};var fh=function(a){fh[" "](a);return a};fh[" "]=function(){};var hh=function(a,b){var c=gh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ih=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},jh=function(a,b){return a<b?-1:a>b?1:0};var kh;a:{var lh=ib.navigator;if(lh){var mh=lh.userAgent;if(mh){kh=mh;break a}}kh=""}var X=function(a){return-1!=kh.indexOf(a)};var nh=function(){X("iPod")},oh=function(){return X("iPhone")&&!X("iPod")&&!X("iPad")};var ph=X("Opera"),qh=X("Trident")||X("MSIE"),rh=X("Edge"),sh;if(sh=X("Gecko")){var th=kh.toLowerCase();sh=!(-1!=th.indexOf("webkit")&&!X("Edge"))}var uh=sh&&!(X("Trident")||X("MSIE"))&&!X("Edge"),vh=kh.toLowerCase(),wh=-1!=vh.indexOf("webkit")&&!X("Edge");wh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var xh=ib.navigator||null;xh&&(xh.appVersion||"").indexOf("X11");X("Android");oh();X("iPad");nh();oh()||X("iPad")||nh();
var yh=function(){var a=ib.document;return a?a.documentMode:void 0},zh;a:{var Ah="",Bh=function(){var a=kh;if(uh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(rh)return/Edge\/([\d\.]+)/.exec(a);if(qh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(wh)return/WebKit\/(\S+)/.exec(a);if(ph)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Bh&&(Ah=Bh?Bh[1]:"");if(qh){var Ch=yh();if(null!=Ch&&Ch>parseFloat(Ah)){zh=String(Ch);break a}}zh=Ah}
var Dh=zh,gh={},Eh=function(a){return hh(a,function(){for(var b=0,c=ih(String(Dh)).split("."),d=ih(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=jh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||jh(0==k[2].length,0==l[2].length)||jh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Fh;
var Gh=ib.document;Fh=Gh&&qh?yh()||("CSS1Compat"==Gh.compatMode?parseInt(Dh,10):5):void 0;var Hh;if(!(Hh=!uh&&!qh)){var Ih;if(Ih=qh)Ih=9<=Number(Fh);Hh=Ih}Hh||uh&&Eh("1.9.1");qh&&Eh("9");var gb=function(a,b){var c="";qh&&!Jh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Kh)a.srcdoc=d;else if(Lh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Mh(a,d)},Kh=wh&&"srcdoc"in document.createElement("iframe"),Lh=uh||wh||qh&&Eh(11),Mh=function(a,b){qh&&Eh(7)&&!Eh(10)&&6>Nh()&&Oh(b)&&(b=Ph(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};qh&&!Jh(a)?Qh(a,c):c()},Nh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Jh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{fh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Rh=0,Qh=function(a,b){var c="goog_rendering_callback"+Rh++;ib[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Oh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Ph=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Th=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=Th(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=L.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,Za(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);Th(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){u(d)}}};var Vh=function(a,b,c){if(L.body){var d=
a[fd];d instanceof cb&&(d=d.resolve(db(b,c)),b=eb);if(a[cf])try{gb(ea(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),u(b)}catch(e){u(c)}else a[ef]?Uh(d,b,c):Th(L.body,hb(d),b,c)()}else z.setTimeout(function(){Vh(a,b,c)},200)},_html=Vh;_html.a="html";_html.b=["customScripts"];
var gi=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=di(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=ei(f,g);fi(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},hi=null,di=function(a){if(hi)return hi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return hi=
c}0==a.styleSheets.length&&a.createStyleSheet();return hi=a.styleSheets[0]},ei=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},fi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var oi={},pi=void 0,qi=function(a){var b=oi[a];b||(b={id:a,w:[],ca:0,Oa:null,Da:void 0,Ha:!1},oi[a]=b);pi=b},si=function(a,b,c,d){var e=pi;if(!sg||!e)return!1;var f={id:e.id+":"+e.w.length,pb:b,Y:[],kb:c,I:a,za:0,xa:d||null,Va:0,ba:!1};e.w.push(f);null===a?(f.ba=!0,b(null)):ri(e);return!0},ti=function(a){var b=gi(a,"visibility","hidden",!0);return function(){P(b)&&b.apply();b=null}},ui=function(a,b,c,d){var e=b;if(!ab){var f=ti(a.B);bb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return si(a,
e,c,d)},ri=function(a){if(!a.Ha){for(var b=a.ca;b<a.w.length;b++){var c=a.w[b],d=b==a.ca;if(!c.ba&&!vi(d,c))break;c.ba&&d&&a.ca++}a.w.length>a.ca?(a.Oa||(a.Oa=z.setTimeout(function(){a.Oa=null;ri(a)},80)),ab||a.Da||(a.Da=function(){u(function(){ri(a)})},U(L,"DOMContentLoaded",a.Da))):wi(a)}},wi=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.I)for(var d=fa(c.I.B)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(xi(f,c.id),c.Y.push(yi(f,c.id)))}}},
vi=function(a,b){var c=[];if(b.I){var d=zi(b.I,b.id),e=null;b.xa&&(e=zi(b.xa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ab&&(null===b.xa.u||b.Va+c.length<b.xa.u)))break;c.push({element:g,bc:h})}}if(!ab&&b.kb&&(!a||null==b.I.u||b.I.u!=b.za+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].bc,n;b.za++;xi(l,b.id);m&&(b.Va++,n=b.id+"-t",xi(m,n));var q=b.pb(l,m);P(q)&&b.Y.push(q);b.Y.push(yi(l,b.id));m&&n&&b.Y.push(yi(m,n))}if(b.I.u&&
b.I.u==b.za||ab)b.ba=!0;return!0},xi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},yi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},zi=function(a,b){for(var c=fa(a.B)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.G&&!Ai(f))break;d.push(f)}}return d},Ai=function(a){if(ab)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ha,Bi,Ci,Na=/(Firefox\D28\D)/g.test(Ef.userAgent),Ei=function(a,b){return function(c){c=c||z.event;var d=Qa(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Ra(d,["a","area"]),e=!d||!d.href||Di(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Ha:Ci;if(c.defaultPrevented||!1===c.returnValue||c.da&&c.da()){if(d){var g={simulateDefault:!1},h=Ia(f,["wnc","nwnc"]);h&&Ja(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=Ia(f,
["wnc","nwnc","nwc","wc"]);(k=Ja(a,d,g,f.wt,l))||(Ka(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Na;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Oa(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Ja=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ha(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Fi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Gi(b);g.eventTimeout=f;g.eventCallback=Hi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ra(g)},
Gi=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Ma=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Oa=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Ef.userAgent),e=Ma(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=z.frames&&z.frames[f]||z[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+I().getTime(),b.targetWindow=z.open("",b.targetWindowName));break;default:d&&!z.frames[e]?(b.simulateDefault=!1,c=!0):(z.frames[e]||(b.targetWindowName=e),b.targetWindow=z.frames[e]||z.open("",e))}return c},Fi=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||I().getTime(),500>I().getTime()-c&&z.setTimeout(Fi(a,b,c),25)))}},Hi=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);L.gtmSubmitFormNow=!0;La(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||I().getTime(),500>I().getTime()-c&&z.setTimeout(Hi(a,b,c),25)}},Ia=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Ii=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Ka=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ji.length;c++)if(a.passingRules[c]){var d=Ki[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ji[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},pa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(L.gtmHasClickListenerTag)return;L.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Qa(a);b&&Ja("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Bi&&(Bi=na(L.location));Ii(Ci,b||!1,c||!1,d,e);if(L.gtmHasLinkClickListenerTag)return;
L.gtmHasLinkClickListenerTag=!0;f="click";g=Ei(a,b||!1);break;case "FORM_SUBMIT":Ii(Ha,b||!1,c||!1,d,e);if(L.gtmHasFormSubmitListenerTag)return;L.gtmHasFormSubmitListenerTag=!0;f="submit";g=Ei(a,b||!1);break;default:return}U(L,f,g,h)},Di=function(a){if(!Bi)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ma(a);return Bi==na(c)},La=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
L.gtmFormElementSubmitter||(L.gtmFormElementSubmitter=L.createElement("form"));return L.gtmFormElementSubmitter.submit.call?L.gtmFormElementSubmitter.submit:a.submit},Li=function(){var a=function(a){var b=S("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Ci=a("linkClickMap");Ha=a("formSubmitMap")};var za=function(a,b){var c=b||ib,d=c.onerror,e=!1;wh&&!Eh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,bb:h,tc:k,error:l});return e}};var fj=function(a){if(!a)return!1;if(a[Ab]&&T(a[V])){for(var b=a[V],c=0;c<b.length;c++)if(a[V]=b[c],sf(a))return!0;return!1}return sf(a)};var Aj=43,Bj=[],Cj=[],Dj=[],Ej=new rf,Fj=[],Z=[],Ji=[],Ki=[],Gj=function(){this.O=[]};Gj.prototype.set=function(a,b){this.O.push([a,b]);return this};Gj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.O.length;d++){var e=Hj(this.O[d][0],a,b),f=Hj(this.O[d][1],a,b);c[e]=f}return c};var Ij=function(a){this.index=a};Ij.prototype.resolve=function(a,b){var c=Dj[this.index];if(c&&!b(c)){var d=c[Ea];if(a){if(a.get(d))return;a.set(d,!0)}c=Hj(c,a,b);a&&a.set(d,!1);return sf(c)}};
var _M=function(a){return new Ij(a)},Jj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Hj(Bj[a[f]],b,c);g===Ua&&(e=!0);d.push(g)}return e?new cb(d):d.join("")}},_T=function(a){return new Jj(arguments)},Kj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Hj(a[0],c,d);if(a[0]instanceof Ij&&b(8)&&b(16)){if(e===Ua)return e;var f=sa();Ej.set(f,e);return'google_tag_manager["GTM-WLCZGN"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Kj(arguments)},Lj=function(a,b){this.A=a;this.wa=b},_R=function(a,b){return new Lj(a,b)};
var Hj=function(a,b,c){var d=a;if(a instanceof Ij||a instanceof Gj||a instanceof Jj||a instanceof Kj)return a.resolve(b,c);if(!(a instanceof Lj))if(T(a))for(var d=[],e=0;e<a.length;e++)d[e]=Hj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Hj(a[f],b,c))}return d},Oj=function(){for(var a=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js','',_html,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(){function e(a){a+\x3d\x22\\x3d\x22;for(var d\x3ddocument.cookie.split(\x22;\x22),c\x3d0;c\x3cd.length;c++){for(var b\x3dd[c];\x22 \x22\x3d\x3db.charAt(0);)b\x3db.substring(1);if(-1!\x3db.indexOf(a))return b.substring(a.length,b.length)}return\x22\x22}atl_sio\x3d{identify:function(){var a\x3de(\x22__aid_user_id\x22),d\x3de(\x22__atl_path\x22);if(decodedUserId\x3ddecodeURIComponent(a),\x22\x22!\x3da){var c\x3de(\x22_sio\x22);-1\x3d\x3dc.indexOf(a)\x26\x26analytics.identify(decodedUserId,null,{atl_path:d})}}}}();\x3c/script\x3e\n\n\x3cscript type\x3d\x22text/gtmscript\x22\x3eatl_sio.identify();\x3c/script\x3e',1,_v,'element classes','gtm.elementClasses','element','gtm.element','element target','gtm.elementTarget','element id','gtm.elementId','history old state','gtm.oldHistoryState','element url','gtm.elementUrl','history new state','gtm.newHistoryState',_et,'element text','history old url fragment','gtm.oldUrlFragment','history change source','gtm.historyChangeSource','history new url fragment','gtm.newUrlFragment','url path','path','url hostname','host','event',_f,'referrer'],b=[],c=0;c<a.length;c++)b[c]=
Nj(c,a);return b},Nj=function(a,b){var c=b[a],d=c;if(c instanceof Ij||c instanceof Kj||c instanceof Jj||c instanceof Lj)d=c;else if(T(c))for(var d=[],e=0;e<c.length;e++)d[e]=Nj(c[e],b);else if("object"==typeof c){var d=new Gj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Nj(c[f],b))}return d},Qj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Bj[e[1]]);if(1==a)for(var f=Pj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Cj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Pj(e[g]);3==a&&(c[d]=Bj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Bj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Pj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Aj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);
2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Rj=function(a,b,c){a.push.apply(a,Qj(b,c))};var Sj;
var gg=function(){},Yj=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=Wj[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},
ck=function(a){},jg=function(){},dk=function(a){},ek=function(a,b){},fk=function(a,b){},hg=function(a){};var gk,hk;
var tk=function(a){return function(){}},uk=function(a){return function(){}};var vk=function(a){var b=this;this.g=a;this.Z=this.hb=!1;this.va=[];this.qa=[];this.W=function(){if(b.i&&b.i.event){var c=b.i.event,d=b.g;}b.Z||yf(b.va);Bf(b,1);if(pb[a])for(var e=0;e<pb[a].length;e++)pb[a].shift().W()};this.V=function(){if(b.i&&b.i.event){var c=b.i.event,d=b.g;}b.Z||yf(b.qa);
Bf(b,2);if(pb[a])for(var e=0;e<pb[a].length;e++)pb[a].shift().V()};this.C=eb},wk=function(a,b){a.va.push(b)},xk=function(a,b){a.qa.push(b)},yk=function(a){this.K=[];this.La=[];this.Xa={};this.cb=[];this.U=0;this.Ja={};this.Na={};this.Ma={};this.event=a};yk.prototype.addListener=function(a){this.cb.push(a)};
var zk=function(a){0<a.U||yf(a.cb)},Ak=function(a,b,c,d,e,f){if(!c.Z){a.K[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=T(d)?d.slice():["or",d];e=T(e)?e.slice():[e];f=T(f)?f.slice():[f];a.Xa[b]=d;a.Ja[b]=0<e.length;a.Na[b]=0<f.length;a.U++;var g=function(){0<a.U&&!a.Ja[b]&&!a.Na[b]&&a.U--;zk(a)};wk(c,g);xk(c,g)}},Fk=function(a){for(var b=[],c={},d=0;d<a.K.length;c={P:c.P},d++)if(c.P=a.K[d],c.P){var e=a.Xa[d],f=a.Ja[d],g=a.Na[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Bk(e,c.P.C),
k=0;k<e.length;k++)e[k]instanceof Lj&&e[k].A!=d&&Ck(a,e[k].A,h);(f||g)&&Dk(a,d,function(a){return function(){0<a.P.i.U&&a.P.i.U--;zk(a.P.i)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.K[b[d]].C();for(d=0;d<a.La.length;d++){var l=a.La[d];Ek(l);0<l.length&&l[0].C()}},Ck=function(a,b,c){a.K[b]&&(wk(a.K[b],function(){c(b,!0)}),xk(a.K[b],function(){c(b,!1)}))},Bk=function(a,b){var c=eb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Lj&&a[h].A===e||a[h]===e){g=h;break a}g=
-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Dk=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Z[b];if(a.event.f(h)){}else g=Gk(h,b,a.event.f,a);if(c=g){var k=Hk(b,!0);0<k.length&&f(k[0].A);d.push(c);var l=Hk(b,!1);0<l.length&&f(l[0].A)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Hk(h.g,!0);if(0<k.length){var l=d[g-1],m=Ik(h);wk(l,m);0==k[0].wa?xk(l,m):xk(l,c)}var n=Hk(h.g,!1);0<n.length&&(m=Ik(d[g+1]),wk(h,m),0==n[0].wa?xk(h,m):xk(h,c))}wk(d[d.length-1],c);xk(d[d.length-1],c);a.La.push(d)}},Hk=function(a,b){var c=b?qe:He,d=Z[a],e=void 0===d[c]?[]:d[c];return T(e)?e:[e]},Ik=function(a){return function(){a.C()}},Ek=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.g,f=ob[e],g=f.firingOption;0!=g&&(1==g&&void 0!==
d.i.Ma[e]||2==g&&void 0!==f.state)&&b.push(d)}var h=Jk(b),k;for(k in h)if(h.hasOwnProperty(k)){for(var l=void 0,m=void 0,n=h[k],q=n[0],w=n[n.length-1],y,t=0;t<a.length;t++){var x=a[t];!l&&x.g==q&&0<t&&(l=a[t-1]);x.g==w&&t<a.length-1&&(m=a[t+1]);if(-1<pf(n,x.g))if(y=a.splice(t,1)[0],x.g==w)break;else t--}if(y){var C=Number(k),A=l,B=m;if(A){var J=A.va[0],F=A.qa[0],D=A;D.va=[];D.qa=[];wk(A,J);xk(A,F)}if(A&&B){var E=Ik(B);wk(A,E);var G=Hk(A.g,!1);0<G.length&&G[0].A!=C&&0==G[0].wa&&xk(A,E);var M=Hk(B.g,
!0);0<M.length&&M[0].A!=C&&0==M[0].wa&&xk(A,E)}}}},Jk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Hk(a,!0);0<b.length&&f(b[0].A);e.push(a);var c=Hk(a,!1);0<c.length&&f(c[0].A)};f(d.g);b[d.g]=e}Kk(a,b);return b},Kk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<pf(b[e],d)){delete b[d];break}}};var Mk=function(a,b,c){return function(){a[bd]=b.W;a[cd]=b.V;var d=b.g,e=b.i&&b.i.Ma[d],f=ob[d]&&ob[d].state,g=e?void 0!==e:b.hb||b.Z,h=ob[d]&&ob[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Bf(b,0);var m=b.i?b.i.event:void 0;a=Lk(a,c);if(m){var n=a;ek(m,d)}sf(a,b.W,b.V)}else k&&0==f||l&&0==e?pb[d].push(b):k&&1==f||l&&1==e?b.W():b.V()}},Lk=function(a,b){a=Hj(a,new rf,b);return a},Gk=function(a,b,c,d){var e=d&&d.K,f;if(f=e)a:{if(e&&T(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].g===b){f=e[g];break a}f=void 0}var h=f||new vk(b);h.i=d;wk(h,tk(a));xk(h,uk(a));h.C=Mk(a,h,c);return h};var Rk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Fj[b]&&Hj(Fj[b],new rf,c),e=d;d&&(e=fj(d));a[b]=[e,d]}return a[b]}},bk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.T(c[d],a.f)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.T(e[d],a.f)[0])return!1;return!0},Sk=function(a){for(var b=new yk(a),c=0;c<Aj;c++)if(a.la[c]&&!a.ua[c])if(a.f(Z[c])){}else{var d=a.X[c],e=Gk(d,c,a.f,b);Ak(b,c,e,d[zc],d[qe],d[He]);if(d[qb])break}b.addListener(a.ma);Fk(b);zk(b)},Tk=!1,bg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Tk)return!1;Tk=!0;break;case "gtm.sync":if(W("gtm.snippet")!=mb)return!1}for(var f={id:a,name:b,ma:d||eb,la:Pj(),ua:Pj(),T:Rk(),f:rg(c)},g=[],h=0;h<Ji.length;h++)if(bk(f,Ji[h])){g[h]=!0;for(var k=
f,l=Ji[h],m=l[1],n=0;n<m.length;n++)k.la[m[n]]=!0;for(var q=l[3],n=0;n<q.length;n++)k.ua[q[n]]=!0}else g[h]=!1;ek(f);var y=[];for(var t=0;t<Aj;t++)if(f.la[t]&&!f.ua[t])if(f.f(Z[t])){}else{y[t]=Z[t];}f.X=y;Sk(f);e&&P(e)&&e({passingRules:g,resolvedTags:f.X});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var F in f.X)if(f.X.hasOwnProperty(F)){var D=f.X[F],E;if(!(E=void 0==D[Ea])){var G=D[Ea];E=!("function"!=typeof String.prototype.startsWith?0===G.indexOf("_implicit"):G.startsWith("_implicit"))}if(E)return!0}return!1};var Vk=function(){};var Wk=function(){};var Uk={macro:function(a){if(Ej.contains(a))return Ej.get(a)}};Uk.dataLayer=Qf;Uk.onHtmlSuccess=eh(!0);Uk.onHtmlFailure=eh(!1);Uk.callback=function(a){Ba.hasOwnProperty(a)&&P(Ba[a])&&Ba[a]();delete Ba[a]};
Uk.wb=function(){var a=z.google_tag_manager;a||(a=z.google_tag_manager={});Va=a;if(a["GTM-WLCZGN"]){var b=Va.zones;b&&b.registerNatural("GTM-WLCZGN")}else{a["GTM-WLCZGN"]=Uk;Li();Bj.push.apply(Bj,Oj());Rj(Cj,0,"3:0,3:1,5:2,0:3,1:4,3:5,3:6,5:7,0:8,1:9,3:11,4:12,7:13,3:14,5:15,6:16,5:17,6:18,5:19,6:20,5:21,6:22,5:23,6:24,5:25,6:26,5:27,6:28,3:29,5:30,5:31,6:32,5:33,6:34,5:35,6:36,5:37,2:38,5:39,2:40,5:41,3:42,5:43");Rj(Dj,1,"G,AD,AAO,AAy,AACD,AACM,AACw,AACAD,AACAM,AAAAw,AACAAD,AACAAM,AACAAw,CAAAAAD,CAAAAAM,ABAAAAQ,AAAAAAgB");Rj(Fj,1,"Z,gM");Rj(Z,1,"AwB");Rj(Ji,2,"D:B::");Rj(Ki,4,"10:");for(var c=0;c<Z.length;c++){var d=Z[c],
e=1;d[Od]?e=2:d[Ze]&&(e=0);ob[c]={firingOption:e,state:void 0};pb[c]=[]}Yf();mg();var n=z;if("interactive"==L.readyState&&!L.createEventObject||"complete"==L.readyState)Gf();else{U(L,"DOMContentLoaded",Gf);U(L,"readystatechange",Gf);if(L.createEventObject&&L.documentElement.doScroll){var q=!0;try{q=!n.frameElement}catch(w){}q&&
If()}U(n,"load",Gf)}"complete"===L.readyState?Lf():U(z,"load",Lf);Wk();Vk()}};Uk.wb();var _vs="res_ts:1409629606175000,srv_cl:153082779,ds:live,cv:10";
})()
